### ISSUE TITLE
Pilon on Nanopore assembly of tetraploid organism

### ISSUE THREAD

**Issue by ms-gx** [broadinstitute/pilon#123]
We would like to polish a Nanopore assembly of a tetraploid (vertrbrate).

Does anyone have any experience with this, since Pilon does only offer haploid or diploid as ploidy modes.

**Comment by w1bw** [comment]
For doing consensus base polishing, Pilon should be able to help. However, I would stick to "--fix bases", since the reassembly mechanism won't perform well with poloploid data, and will just slow things down. If you do multiple iterations, you might want to look at the VCF data at the end, which could give you a clue for where there is variation in one of the haplotypes by looking at the QP and  BC fields.
