### ISSUE TITLE
is Pilon OK with 454 data?

### ISSUE THREAD

**Issue by dcopetti** [broadinstitute/pilon#17]
Hello,
I will have to polish and check the reliability of an assembly (I used Falcon and polished with Quiver), and the only short read data I have for this project is some 454 data (3 and 20 kb MP, single reads): will Pilon be OK with the 454 error model?
Thanks,
Dario

**Comment by w1bw** [comment]
Hi Dario,

It has been years since I've tried 454 data with Pilon.  My worry would be
that it could introduce spurious indel corrections, especially around
homopolymer runs.

However, there's a good chance the next release will include the ability to
control whether SNPs and Indels are corrected separately, that that might
help for 454 data.

If you try it, take a look at the corrections Pilon makes and see whether
they look right.

--bruce

**Comment by dcopetti** [comment]
Thanks,
I will test it again in the future with a new release.
