### ISSUE TITLE
Clean metagenomics contigs

### ISSUE THREAD

**Issue by davidvilanova** [broadinstitute/pilon#31]
Hello,
Is pilon suitable to polish metagenome contigs (e.g a community mock). Or do you have to split your contigs into bins and clean up bin contigs ??

Thanks,
david

**Comment by w1bw** [comment]
Sorry for the long delay, but I am finally catching up with Pilon support issues.

Pilon was certainly not intended for metagenomic read data, and while you might get some benefit from it, the heuristics presume we're dealing with reads from a clonal sample.  We at the Broad are working on some new tools for this use case now, but nothing useable yet.

If you do try it, please let me know how it comes out!

**Comment by sapuizait** [comment]
Hi there, I was wondering if there are any updates on the matter. I had a quick look around and noticed that people use pilon for metagenomic assemblies (one published, one study in bioarchives). As far as i understand, this is because there is nothing better out there to correct miassasemblies of short reads. But is there an alternative? sth that is faster than pilon and more suitable for metagenomic data?
