### ISSUE TITLE
Question about --diploid parameter flag

### ISSUE THREAD

**Issue by chad388** [broadinstitute/pilon#77]
Hi,

I was wondering if you could provide more information on what the --diploid parameter flag does?

On the Pilon wiki page, it indicates that this option will eventually affect the calling of heterozygous SNPs, which suggests that this parameter might have been in development at the time that the wiki was written. If I am running Pilon on the primary contigs and haplotigs from a Falcon Unzip assembly, I am guessing that I should probably include the --diploid flag, but I wanted to find out more about how it affected the calling of heterozygous SNPs.

Thanks,

Chad

**Comment by w1bw** [comment]
Hi Chad, I'm finally catching up on long overdue Pilon support. 

Really, the only thing "--diploid" does is affect whether to report hererozygous SNPs and small indels. Since many of the initial Pilon applications were bacterial, by default it treats mixed evidence as ambiguous rather than as a heterozygous SNP or indel. Pilon's support for diploid calls isn't very sophisticated; in particular, it isn't able to generate multiple haplotypes through local reassembly (it's only calling heterzygosity via the alignment pileup information).  Good luck!
